code = {
    373: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    374: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    375: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    376: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    377: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    378: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    379: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    380: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    381: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    287: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity", "phase_code": 6},
    244: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    245: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    246: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    247: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    248: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    249: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    251: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    252: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    253: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence", "phase_code": 2},
    277: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    278: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    279: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    280: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    281: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    282: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    283: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    284: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    285: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    286: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation", "phase_code": 3},
    255: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    257: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    258: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    259: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    260: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    261: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    262: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    263: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    264: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    265: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation", "phase_code": 3},
    290: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    291: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    292: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    293: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    294: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    295: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    296: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    288: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    274: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    289: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    298: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    299: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    300: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    305: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    306: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    307: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    308: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    309: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    311: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    312: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking", "phase_code": 4},
    297: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    355: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    356: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    357: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    358: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    359: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    360: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    361: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    362: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    363: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    313: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    364: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    365: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    366: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    367: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    368: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    369: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    370: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    371: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5},
    372: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence", "phase_code": 5}
}

