code = {
    373: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    374: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    375: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    376: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    377: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    378: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    379: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    380: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    381: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    287: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": ">140", "phase": "Maturity "},
    244: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    245: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    246: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    247: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    248: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    249: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    251: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    252: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    253: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "30-59", "phase": "Emergence "},
    277: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    278: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    279: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    280: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    281: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    282: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    283: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    284: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    285: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    286: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "60-69", "phase": "Tuber Initiation "},
    255: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    257: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    258: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    259: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    260: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    261: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    262: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    263: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    264: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    265: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "70-79", "phase": "Tuber Initiation "},
    290: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    291: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    292: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    293: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    294: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    295: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    296: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    288: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    274: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    289: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "80-89", "phase": "Early Flowering / Early Bulking "},
    298: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    299: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    300: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    305: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    306: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    307: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    308: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    309: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    311: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    312: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "90-99", "phase": "Early Flowering / Early Bulking "},
    297: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    355: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    356: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    357: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    358: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    359: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    360: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    361: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    362: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    363: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "100-109", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    313: {"crop": "POTATO", "variety": "GENERIC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    364: {"crop": "POTATO", "variety": "KENNEBEC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    365: {"crop": "POTATO", "variety": "ATLANTIC", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    366: {"crop": "POTATO", "variety": "NORLAND", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    367: {"crop": "POTATO", "variety": "NORKOTA", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    368: {"crop": "POTATO", "variety": "SHEPODY", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    369: {"crop": "POTATO", "variety": "R. BURBANK", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    370: {"crop": "POTATO", "variety": "SNOWDEN", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    371: {"crop": "POTATO", "variety": "ONAWAY", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "},
    372: {"crop": "POTATO", "variety": "SUPERIOR", "sample_type": "PETIOLE", "days_after_planting": "110-139", "phase": "End of Flowering / Peak Bulking / Beginning Senescence "}
}

